name: Build Translation Test

on:
  push:
    branches:
      - "main"
      - "Uploads"
      - "20*"
    paths:
      - 'Translation/**'
  pull_request:
    branches:
      - "*"
    paths:
      - 'Translation/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v5
      - name: Install dependencies
        uses: ./.github/workflows/InstallDependencies
      - run: ${{ github.workspace }}/L10nUtilTools.bat BD_TEST
      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: NVDA_TranslationTest
          path: ${{ github.workspace }}/Preview/Test/*

